name: AndroidBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.1

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # Add this step to change permissions

      - name: Run Lint
        run: ./gradlew lintDebug  # Run lint command

      - name: Upload html test report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html




#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4.2.1
#
#      - name: Setup Java JDK
#        uses: actions/setup-java@v4.4.0
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Grant execute permission for Gradle wrapper
#        run: chmod +x ./gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v4.4.1
#        with:
#          name: AndroidCICD.apk
#          path: app/build/outputs/apk/debug/app-debug.apk
