name: AndroidBuild
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Grdle
        uses: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.1
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/app/app-debug.apk
