name: AndroidBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload HTML lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 24
          build-tools: 30.0.2

      - name: List available devices
        run: adb devices

      - name: Set physical device (optional)
        run: |
          # Replace the following with the actual device serial number obtained from 'adb devices'
          DEVICE_SERIAL=1234567890  
          adb -s $DEVICE_SERIAL wait-for-device

      - name: Run tests on physical device
        run: |
          # Replace the following with the actual device serial number obtained from 'adb devices'
          DEVICE_SERIAL=1234567890  
          adb -s $DEVICE_SERIAL shell am instrument -w com.yehiya.androidcicd/androidx.test.runner.AndroidJUnitRunner
        env:
          ANDROID_SERIAL: $DEVICE_SERIAL  # Set this environment variable to ensure Gradle uses the correct device

      - name: Upload HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/debug/







#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4.2.1
#
#      - name: Setup Java JDK
#        uses: actions/setup-java@v4.4.0
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Grant execute permission for Gradle wrapper
#        run: chmod +x ./gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Upload a Build Artifact
#        uses: actions/upload-artifact@v4.4.1
#        with:
#          name: AndroidCICD.apk
#          path: app/build/outputs/apk/debug/app-debug.apk
